name: master and pr builds
on:
  push:
  pull_request:
    branches: 
    - master
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Set flag from Commit"
        env:
          IS_MAIN: ${{ contains(github.event.ref, 'master') }}
        run: |
          if ${IS_MAIN} == true; then
            echo "label=latest" >> $GITHUB_ENV
            echo "label set to 'latest'"
          else
            echo "label=unstable" >> $GITHUB_ENV
            echo "label set to 'unstable'"
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cve-search:${{ env.label }}
          # build-args: |
          #   arg1=value1
          #   arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}